INSERT INTO `traveldreamsystem_db`.`escursione` (`IDPRODBASE`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`, `LUOGO`) 
										 VALUES ('1', '10', '2013-11-27 23:44:12', '2013-11-27 23:44:13','escursione in barca: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'genova');
INSERT INTO `traveldreamsystem_db`.`escursione` (`IDPRODBASE`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`, `LUOGO`)
										 VALUES ('2', '10', '2013-11-27 23:44:12', '2013-11-27 23:44:13','escursione in aereo: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'genova');
INSERT INTO `traveldreamsystem_db`.`escursione` (`IDPRODBASE`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`, `LUOGO`)
										 VALUES ('3', '10', '2013-11-27 23:44:12', '2013-11-27 23:44:13','escursione in sottomarino: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', 'genova');
INSERT INTO `traveldreamsystem_db`.`hotel` (`IDPRODBASE`, `CITTA`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`, `STELLE`, `TIPOCAMERA`)
									VALUES ('4', 'napoli', '100', '2013-11-27 23:44:12', '2013-11-27 23:44:13','vista mare: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '3', '3');
INSERT INTO `traveldreamsystem_db`.`hotel` (`IDPRODBASE`, `CITTA`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`, `STELLE`, `TIPOCAMERA`)
									VALUES ('5', 'caserta', '100', '2013-11-27 23:44:12', '2013-11-27 23:44:13','vista reggia: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.', '4', '4');
INSERT INTO `traveldreamsystem_db`.`trasporto` (`IDPRODBASE`, `CITTAPARTENZA`, `CITTARITORNO`, `COSTO`, `DATAPARTENZA`, `DATARITORNO`, `DESCRIZIONE`) 
										VALUES ('6', 'milano', 'roma', '65', '2013-11-27 23:44:12', '2013-11-27 23:44:13','aeroplano: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO `traveldreamsystem_db`.`pacchpred` (`IDPACCHPRED`, `DESCRIZIONE`) 
										VALUES ('1', 'vacanza di prova: Lorem ipsum dolor sit amet, consectetur adipisici elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat. Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.');
INSERT INTO `traveldreamsystem_db`.`escursionipacchpred` (`IDESCURSIONE`, `IDPACCHPRED` ) 
												  VALUES ('1', '1');
INSERT INTO `traveldreamsystem_db`.`escursionipacchpred` (`IDESCURSIONE`, `IDPACCHPRED` ) 
												  VALUES ('2', '1');
INSERT INTO `traveldreamsystem_db`.`escursionipacchpred` (`IDESCURSIONE`, `IDPACCHPRED` ) 
												  VALUES ('3', '1');
INSERT INTO `traveldreamsystem_db`.`hotelspacchpred` (`IDHOTEL`, `IDPACCHPRED` ) 
											 VALUES ('4', '1');
INSERT INTO `traveldreamsystem_db`.`hotelspacchpred` (`IDHOTEL`, `IDPACCHPRED` ) 
											 VALUES ('5', '1');
INSERT INTO `traveldreamsystem_db`.`trasportipacchpred` (`IDTRASPORTO`, `IDPACCHPRED` ) 
											     VALUES ('6', '1');												  